
language: java
sudo: true
dist: trusty
jdk: openjdk12

before_install:
  - chmod +x mvnw
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
