sudo: required

language: java

matrix:
  include:

    - env: DEPLOY='linux'
      jdk: openjdk11
      
    - env: DEPLOY='linux-12-early-access'
      jdk: openjdk12

    - env: DEPLOY='linux-early-access'
      jdk: openjdk-ea

    - env: DEPLOY='false'
      jdk: oraclejdk11

    - env: DEPLOY='macos'
      os: osx
      jdk: openjdk11
      
    - env: DEPLOY='macos-12-early-access'
      os: osx
      jdk: openjdk12

    - env: DEPLOY='macos-early-access'
      os: osx
      jdk: openjdk-ea

    - env: DEPLOY='linux-early-access-loom' TAG="untagged-014eac50b5442f2f855f" NAME="jdk-13-loom"
      
    - env: DEPLOY='linux-early-access-amber' TAG="untagged-014eac50b5442f2f855f" NAME="jdk-13-amber"
      
    - env: DEPLOY='linux-early-access-lworld' TAG="untagged-014eac50b5442f2f855f" NAME="jdk-13-lworld"
      
    - env: DEPLOY='macos-early-access-loom' TAG="untagged-014eac50b5442f2f855f" NAME="jdk-13-loom"
      os: osx
      
    - env: DEPLOY='macos-early-access-amber' TAG="untagged-014eac50b5442f2f855f" NAME="jdk-13-amber"
      os: osx
      
    - env: DEPLOY='macos-early-access-lworld' TAG="untagged-014eac50b5442f2f855f" NAME="jdk-13-lworld"
      os: osx

#  allow_failures:
#    - jdk: openjdk-ea

before_install:
  - if [[ -n $TAG ]]; then wget https://github.com/forax/java-next/releases/download/$TAG/$NAME-$TRAVIS_OS_NAME.tar.gz   ; fi
  - if [[ -n $TAG ]]; then tar zxvf $NAME-$TRAVIS_OS_NAME.tar.gz   ; fi
  - if [[ -n $TAG ]]; then export JAVA_HOME=$NAME   ; fi
  - if [[ -n $TAG ]]; then export PATH=$JAVA_HOME/bin:$PATH   ; fi

install:
  - java --version

script:
  - chmod u+x ./build.sh
  - ./build.sh
  - if [ "$NAME" == "jdk-13-lworld" ]; then sed -i.bak s/JLINK_VM_OPTIONS=/JLINK_VM_OPTIONS="\"-XX:+EnableValhalla\""/g ./target/pro/bin/pro  ; fi
  - ./target/pro/bin/pro version
  - ./target/pro/bin/pro build test.pro
